# Baselines, Control Parameters, Overlays

## Security Control Baselines.
Armavel has extensive experience in selecting, supplementing, and documenting
security control baselines. Specifically, we have built expertise in identifying the
appropriate security and privacy control baselines as outlined in NIST SP 800-53
& NIST 800-53B. 
While working for VA Digital Transformation Center, our team accomplishments include
 
 * 236 Information System evaluations for NIST 800-145 compliance
 * 209 Information System evaluations for NIST 800-53 / 800-60 Security categorization
 * 83 FedRAMP Initial Application Packages
 * 66 FedRAMP Authorizations to Opperate granted
 * 17 FedRAMP "In Process" designations

Each of the information systems listed above required the expertise of our team to evaluate 
Low , Moderate , or High Impact systems. 

_Baseline_ | _Number of Controls_ | _Sub Controls_
-----------| ---------------- | ---------
Privacy Baseline Controls | 81 | TBD
Low Impact | 131 | TBD
Moderate Impact | 177 | TBD
High Impact | 188 | 1207

Our team has engineered, implemented, and refined processes to maintain granular
control while increasing throughput in Information System evaluation. The result
of such control is the ability to create, adjust, and update documentation
expediently. 
